/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book_shop;
import java.util.*;
/**
 *
 * @author chinn
 */

public class book extends javax.swing.JFrame {

    /**
     * Creates new form book
     */
    Scanner sc = new Scanner(System.in);
    public book() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnaddbook = new javax.swing.JButton();
        btnaddcopies = new javax.swing.JButton();
        btnupdatebook = new javax.swing.JButton();
        btncheckcopies = new javax.swing.JButton();
        btnsearchbyname = new javax.swing.JButton();
        btnsearchbyid = new javax.swing.JButton();
        btnbooktoorder = new javax.swing.JButton();
        btnaddbook8 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Shop");

        btnaddbook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnaddbook.setText("Add Book");
        btnaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbookActionPerformed(evt);
            }
        });

        btnaddcopies.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnaddcopies.setText("Add copies");
        btnaddcopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcopiesActionPerformed(evt);
            }
        });

        btnupdatebook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdatebook.setText("Update book info");
        btnupdatebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatebookActionPerformed(evt);
            }
        });

        btncheckcopies.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncheckcopies.setText("Check copies");
        btncheckcopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckcopiesActionPerformed(evt);
            }
        });

        btnsearchbyname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsearchbyname.setText("Search Book by Name");
        btnsearchbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbynameActionPerformed(evt);
            }
        });

        btnsearchbyid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsearchbyid.setText("Search Book by Id");
        btnsearchbyid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbyidActionPerformed(evt);
            }
        });

        btnbooktoorder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnbooktoorder.setText("Book to order");
        btnbooktoorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbooktoorderActionPerformed(evt);
            }
        });

        btnaddbook8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnaddbook8.setText("Show all data");
        btnaddbook8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbook8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnaddbook, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnbooktoorder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsearchbyid, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addGap(45, 45, 45)
                                .addComponent(btncheckcopies, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnupdatebook)
                                .addGap(83, 83, 83)
                                .addComponent(btnaddcopies, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaddbook8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddbook, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdatebook, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddcopies, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncheckcopies, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchbyid, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbooktoorder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddbook8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbookActionPerformed
        // TODO add your handling code here:
        new addnew().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnaddbookActionPerformed

    private void btnaddcopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcopiesActionPerformed
        // TODO add your handling code here:
        new addcopies().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnaddcopiesActionPerformed

    private void btnupdatebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatebookActionPerformed
        // TODO add your handling code here:
        new update_info().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnupdatebookActionPerformed

    private void btncheckcopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckcopiesActionPerformed
        // TODO add your handling code here:
        new checkcopies().setVisible(true);
        dispose();
    }//GEN-LAST:event_btncheckcopiesActionPerformed

    private void btnsearchbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbynameActionPerformed
        // TODO add your handling code here:
        new searchbyname().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsearchbynameActionPerformed

    private void btnsearchbyidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbyidActionPerformed
        // TODO add your handling code here:
        new searchbyid().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsearchbyidActionPerformed

    private void btnbooktoorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbooktoorderActionPerformed
        // TODO add your handling code here:
        new bookto_order().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbooktoorderActionPerformed

    private void btnaddbook8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbook8ActionPerformed
        // TODO add your handling code here:
        new showdata().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnaddbook8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btnaddbook8;
    private javax.swing.JButton btnaddcopies;
    private javax.swing.JButton btnbooktoorder;
    private javax.swing.JButton btncheckcopies;
    private javax.swing.JButton btnsearchbyid;
    private javax.swing.JButton btnsearchbyname;
    private javax.swing.JButton btnupdatebook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
